services:

  mongodb:
    image: mongo:6.0
    init: true
    volumes:
      - dbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=test_task
    networks:
      - backend

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/test_task
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app
      - maven-repository:/root/.m2:cached
    networks:
      - backend

volumes:
  dbdata:
  maven-repository:

networks:
  backend: